# Generated by Django 4.2 on 2023-04-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatusModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toDoStatus", models.CharField(max_length=255, verbose_name="status")),
            ],
        ),
        migrations.CreateModel(
            name="ToDoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toDoItem", models.TextField(verbose_name="toDo")),
                (
                    "toDoAction",
                    models.BooleanField(default=None, verbose_name="buttons"),
                ),
                (
                    "toDoStatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.statusmodel",
                        verbose_name="status",
                    ),
                ),
            ],
        ),
    ]
