# Generated by Django 4.2 on 2023-04-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="toDoStatus",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="home.statusmodel",
                verbose_name="status",
            ),
        ),
    ]
