# Generated by Django 4.2 on 2023-04-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_todomodel_todostatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="toDoAction",
            field=models.BooleanField(default=False, verbose_name="buttons"),
        ),
    ]
